_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 83469a3a-a58e-4fe8-8ad7-c150440b8924
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node/43
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
